lane :increase_version do
    app_store_connect_api_key(
        key_id: "WSF227H5U3",
        issuer_id: "f42e9e12-3482-46c6-9e4d-d4e11d33de60",
        key_content: "-----BEGIN PRIVATE KEY-----\nMIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgUFL/Cj/8LNLgqQCb1d8xsqo0BVf1YO1RcP4i73LyAtSgCgYIKoZIzj0DAQehRANCAARbDYJ+fTij/ZQXnmBDwsNBY/qOUKh4lJMralZ4mRALaVg3fe34ryNS8ST/8Z+LLFkJn6KuMLtMbH0bGM7sfByf\n-----END PRIVATE KEY-----"
    )

    ios_bundle_version_detail = latest_testflight_build_number(
        username: "SpiralDailyDev@gmail.com",
        app_identifier: "com.spiraldailydev.dailyMemo",
    )

    data = YAML.load_file("/Users/distiller/project/apps/daily_memo/pubspec.yaml")
    ios_bundle_version = data["version"]
    ios_bundle_version = ios_bundle_version.split("+")[0]

    ios_bundle_version_detail += 1

    sh("sed -i '' -e \"s/version: .*/version: #{ios_bundle_version}+#{ios_bundle_version_detail}/\" /Users/distiller/project/apps/daily_memo/pubspec.yaml")

end
lane :upload_binary do
    app_store_connect_api_key(
        key_id: "WSF227H5U3",
        issuer_id: "f42e9e12-3482-46c6-9e4d-d4e11d33de60",
        key_content: "-----BEGIN PRIVATE KEY-----\nMIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgUFL/Cj/8LNLgqQCb1d8xsqo0BVf1YO1RcP4i73LyAtSgCgYIKoZIzj0DAQehRANCAARbDYJ+fTij/ZQXnmBDwsNBY/qOUKh4lJMralZ4mRALaVg3fe34ryNS8ST/8Z+LLFkJn6KuMLtMbH0bGM7sfByf\n-----END PRIVATE KEY-----"
    )

    upload_to_testflight(
        username: "SpiralDailyDev@gmail.com",
        app_identifier: "com.spiraldailydev.dailyMemo",
        ipa: "../build/ios/ipa/apps.daily_memo.ipa"
    )
end

lane :upload_binary_release do
    app_store_connect_api_key(
        key_id: "WSF227H5U3",
        issuer_id: "f42e9e12-3482-46c6-9e4d-d4e11d33de60",
        key_content: "-----BEGIN PRIVATE KEY-----\nMIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgUFL/Cj/8LNLgqQCb1d8xsqo0BVf1YO1RcP4i73LyAtSgCgYIKoZIzj0DAQehRANCAARbDYJ+fTij/ZQXnmBDwsNBY/qOUKh4lJMralZ4mRALaVg3fe34ryNS8ST/8Z+LLFkJn6KuMLtMbH0bGM7sfByf\n-----END PRIVATE KEY-----"
    )
    upload_to_app_store(
        username: "SpiralDailyDev@gmail.com",
        app_identifier: "com.spiraldailydev.dailyMemo",
        ipa: "../build/ios/ipa/apps.daily_memo.ipa",
        submit_for_review: true,
        force: true,
        automatic_release: true,
        skip_screenshots: true,
        skip_metadata: true,
        run_precheck_before_submit: false,
        precheck_include_in_app_purchases: false,
        app_version: "1.0.6"
    )
end

lane :release do
    create_keychain(
        name: "test",
        password: "test",
        timeout: 1800,
        default_keychain: true,
        unlock: true,
        lock_when_sleeps: false
    )

    app_store_connect_api_key(
        key_id: "WSF227H5U3",
        issuer_id: "f42e9e12-3482-46c6-9e4d-d4e11d33de60",
        key_content: "-----BEGIN PRIVATE KEY-----\nMIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgUFL/Cj/8LNLgqQCb1d8xsqo0BVf1YO1RcP4i73LyAtSgCgYIKoZIzj0DAQehRANCAARbDYJ+fTij/ZQXnmBDwsNBY/qOUKh4lJMralZ4mRALaVg3fe34ryNS8ST/8Z+LLFkJn6KuMLtMbH0bGM7sfByf\n-----END PRIVATE KEY-----"
    )

    match(
        git_url: "git@github.com:GBbStar/iOS-Cert.git",
        storage_mode: "git",
        type: "appstore",
        readonly: true,
        keychain_name: "test",
        keychain_password: "test"
    )

end
