version: '2.1'

orbs:
  android: circleci/android@1.0.3
  flutter: circleci/flutter@2.0.2

parameters:
  daily_memo_deploy:
    type: boolean
    default: true
  service-root-path:
    type: string
    default: ""

jobs:
  android-deploy:
    executor:
      name: android/android-machine
      resource-class: medium
    steps:
      - checkout
      - flutter/install_sdk:
          version: 3.10.6
      - run:
          name: Install Fastlane
          command: gem install fastlane
      - run:
          name: Google Service Json Parse(For Firebase)
          command: echo -n $GOOGLE_SERVICE_JSON | base64 --decode > apps/daily_memo/android/app/google-services.json
      - run:
          name: Build AAB Binary
          command: flutter build appbundle
          working_directory: << pipeline.parameters.service-root-path >>
      - run:
          name: Signing AAB
          command: echo -n $PLAYSTORE_KEY_STORE | base64 --decode > apps/daily_memo/keystore.jks
      - run:
          command: jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore apps/daily_memo/keystore.jks -storepass MorethanMore1! -keypass MorethanMore1! apps/daily_memo/build/app/outputs/bundle/release/app-release.aab spiral
      - run:
          name: Google Playstore API Json Parse
          command: echo -n $GOOGLE_PLAYSTORE_API_KEY_JSON | base64 --decode > apps/daily_memo/android/google_playstore_api_key.json
      - run:
          command: fastlane run supply aab:apps/daily_memo/build/app/outputs/bundle/release/app-release.aab track:production json_key:apps/daily_memo/android/google_playstore_api_key.json package_name:com.spiral_daily_dev.apps.daily_memo

  ios-deploy:
    macos:
      xcode: 15.2.0
    steps:
      - checkout
      - flutter/install_sdk:
          version: 3.10.6
      - run:
          name: Install Fastlane
          command: gem install fastlane
      - run:
          name: Install Fastlane
          command: gem install cocoapods
      #      - run:
      #          name: Install dotenv
      #          command: sudo gem install dotenv
      #      - run:
      #          name: set fastlane env
      #          command: cd ios/fastlane/ && echo "APPLE_ID=$APPLE_ID\nFASTLANE_PASSWORD=$APPLE_PW\nFASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD=$APPLE_APPLICATION_SPECIFIC_PASSWORD"
      #          working_directory: << pipeline.parameters.service-root-path >>
      #      - run:
      #          command: echo $SSH_ID | base64 --decode > id_ed25519.pub && sudo ssh-add id_ed25519.pub
      #      - run:
      #          command: fastlane run match type:"appstore" app_identifier:"com.spiraldailydev.dailyMemo" username:"SpiralDailyDev@gmail.com" git_url:"git@github.com:GBbStar/iOS-Cert.git" git_private_key:$GIT_PRIVATE_KEY keychain_name:$MATCH_KEYCHAIN_NAME keychain_password:$MATCH_KEYCHAIN_PASSWORD --verbose
      #          working_directory: << pipeline.parameters.service-root-path >>
      - run:
          command: fastlane release
          working_directory: << pipeline.parameters.service-root-path >>/ios
      - run:
          name:
          command: flutter clean && flutter pub get
          working_directory: << pipeline.parameters.service-root-path >>
      - run:
          name:
          command: pod cache clean --all && pod install
          working_directory: << pipeline.parameters.service-root-path >>/ios
      - run:
          command: fastlane increase_version --verbose
          working_directory: << pipeline.parameters.service-root-path >>/ios
      - run:
          name:
          command: flutter build ipa --release --export-options-plist=ios/export_options.plist
          working_directory: << pipeline.parameters.service-root-path >>
      #      - run:
      #          command: fastlane run appstore
#      - run:
#          command: fastlane upload_binary --verbose
#          working_directory: << pipeline.parameters.service-root-path >>/ios
      - run:
          command: fastlane upload_binary --verbose
          working_directory: << pipeline.parameters.service-root-path >>/ios




workflows:
  daily-memo-deploy-workflow:
    jobs:
      - android-deploy
      - ios-deploy
