name: spiralDev

packages:
  - "apps/*"
  - "packages/**"

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  pub_get:
    run: flutter pub global run melos exec --scope="apps.check_my_life" -- flutter clean && flutter pub global run melos exec --scope="apps.check_my_life" -- flutter pub get
    description: daily memo pub get

  daily_memo_pub_get:
    run: flutter pub global run melos exec --scope="apps.check_my_life" -- flutter clean && flutter pub global run melos exec --scope="apps.check_my_life" -- flutter pub get
    description: daily memo pub get

  daily_memo_test:
    run: flutter pub global run melos exec --scope="apps.daily_memo" -- flutter clean && flutter pub global run melos exec --scope="apps.daily_memo" -- flutter test
    description: daily memo pub get
