// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-Qh329ZMEGg3Q32OtstBsMDmvLtRaj34',
    appId: '1:1015918841200:android:3caaada2265636a86893b5',
    messagingSenderId: '1015918841200',
    projectId: 'mememo-ada5d',
    storageBucket: 'mememo-ada5d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBFs6EQKEDZCVULO1l2mNAPOnclP-QOnU',
    appId: '1:1015918841200:ios:475e1e1fefb14c126893b5',
    messagingSenderId: '1015918841200',
    projectId: 'mememo-ada5d',
    storageBucket: 'mememo-ada5d.appspot.com',
    iosClientId: '1015918841200-vc8nf6e750igf9bu2ta70kitu74ola5j.apps.googleusercontent.com',
    iosBundleId: 'com.example.dailyMemo',
  );
}
