name: app_analytics
description: Shared analytics abstraction for Spiral apps.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.10.0

dependencies:
  app_logging:
    path: ../app_logging

dev_dependencies:
  test: ^1.24.0
  lints: ^3.0.0
