version: '2.1'

orbs:
  flutter: circleci/flutter@2.0.2
  continuation: circleci/continuation@1.0.0
  android: circleci/android@1.0.3

parameters:
  daily_memo_trigger:
    type: boolean
    default: false
  exchange_calculator_trigger:
    type: boolean
    default: false
  service-root-path:
    type: string
    default: ""

jobs:
  flutter-unit-test:
    macos:
      xcode: 14.2.0
    steps:
      - checkout
      - flutter/install_sdk:
          version: 3.3.10
      - run:
          command: flutter test
          working_directory: << pipeline.parameters.service-root-path >>

  flutter-static-analysis:
    macos:
      xcode: 14.2.0
    steps:
      - checkout
      - flutter/install_sdk:
          version: 3.3.10
      - run:
          name: Lint
          command: dart analyze
          working_directory: << pipeline.parameters.service-root-path >>

  flutter-build-apk:
    executor:
      name: android/android-machine
    steps:
      - checkout
      - flutter/install_sdk:
          version: 3.3.10
      - run:
          command: echo -n $GOOGLE_SERVICE_JSON | base64 --decode > android/app/google-services.json
          working_directory: << pipeline.parameters.service-root-path >>
      - run:
          command: flutter clean && flutter build appbundle --release
          working_directory: << pipeline.parameters.service-root-path >>

  flutter-build-ipa:
    macos:
      xcode: 14.2.0
    steps:
      - checkout
      - flutter/install_sdk:
          version: 3.3.10
      - run:
          command: echo -n $GOOGLE_SERVICE_JSON | base64 --decode > android/app/google-services.json
          working_directory: << pipeline.parameters.service-root-path >>
      - run:
          command: flutter clean && flutter build ipa
          working_directory: << pipeline.parameters.service-root-path >>

workflows:
  ci-flow:
    jobs:
      - flutter-unit-test
#      - flutter-static-analysis
      - flutter-build-apk
