name: core_app_shell
description: Common application bootstrap utilities for SpiralDailyDev apps.
version: 0.0.1
publish_to: "none"

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  go_router: ^6.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
