name: networking
description: Shared network layer for Spiral apps.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  dio: ^5.7.0
  meta: ^1.11.0
  utils:
    path: ../utils

dev_dependencies:
  test: ^1.24.0
  lints: ^3.0.0
