require "yaml"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

REPO_ROOT = File.expand_path('..', __dir__)

def load_app_config(app_name)
  config = YAML.load_file(File.join(REPO_ROOT, "release.yaml"))
  app = config.dig("apps", app_name)
  UI.user_error!("App '#{app_name}' not found in release.yaml") unless app
  app
end

def setup_asc_api_key
  app_store_connect_api_key(
    key_id: ENV["ASC_KEY_ID"],
    issuer_id: ENV["ASC_ISSUER_ID"],
    key_content: ENV["ASC_KEY_CONTENT"],
    is_key_content_base64: true
  )
end

# ---------------------------------------------------------------------------
# Android lanes
# ---------------------------------------------------------------------------

platform :android do
  desc "Deploy to Google Play internal track"
  lane :deploy_internal do |options|
    app_name = options[:app]
    UI.user_error!("Missing required parameter :app") unless app_name
    config = load_app_config(app_name)
    app_id = config["appId"]
    project_path = config["projectPath"]

    project_dir = File.join(REPO_ROOT, project_path)

    Dir.chdir(project_dir) do
      sh("flutter", "build", "appbundle", "--release")
    end

    aab_path = File.join(project_dir, "build", "app", "outputs", "bundle", "release", "app-release.aab")

    upload_to_play_store(
      package_name: app_id,
      aab: aab_path,
      track: "internal",
      json_key_data: ENV["GOOGLE_PLAY_SERVICE_ACCOUNT_JSON"],
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  desc "Deploy to Google Play production track"
  lane :deploy_production do |options|
    app_name = options[:app]
    UI.user_error!("Missing required parameter :app") unless app_name
    config = load_app_config(app_name)
    app_id = config["appId"]
    project_path = config["projectPath"]

    project_dir = File.join(REPO_ROOT, project_path)

    Dir.chdir(project_dir) do
      sh("flutter", "build", "appbundle", "--release")
    end

    aab_path = File.join(project_dir, "build", "app", "outputs", "bundle", "release", "app-release.aab")

    upload_to_play_store(
      package_name: app_id,
      aab: aab_path,
      track: "production",
      json_key_data: ENV["GOOGLE_PLAY_SERVICE_ACCOUNT_JSON"],
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end

# ---------------------------------------------------------------------------
# iOS lanes
# ---------------------------------------------------------------------------

platform :ios do
  desc "Deploy to TestFlight"
  lane :deploy_testflight do |options|
    app_name = options[:app]
    UI.user_error!("Missing required parameter :app") unless app_name
    config = load_app_config(app_name)
    ios_bundle_id = config["iosBundleId"]
    project_path = config["projectPath"]

    setup_asc_api_key

    create_keychain(
      name: "fastlane_keychain",
      password: "fastlane_keychain",
      timeout: 1800,
      default_keychain: true,
      unlock: true,
      lock_when_sleeps: false
    )

    match(
      app_identifier: ios_bundle_id,
      type: "appstore",
      readonly: true,
      keychain_name: "fastlane_keychain",
      keychain_password: "fastlane_keychain"
    )

    project_dir = File.join(REPO_ROOT, project_path)

    Dir.chdir(project_dir) do
      sh("flutter", "build", "ipa", "--release", "--export-options-plist=ios/ExportOptions.plist")
    end

    ipa_dir = File.join(project_dir, "build", "ios", "ipa")
    ipa_path = Dir.glob(File.join(ipa_dir, "*.ipa")).first
    UI.user_error!("No .ipa found in #{ipa_dir}") unless ipa_path

    upload_to_testflight(
      app_identifier: ios_bundle_id,
      ipa: ipa_path,
      skip_waiting_for_build_processing: true
    )
  end

  desc "Deploy to App Store"
  lane :deploy_appstore do |options|
    app_name = options[:app]
    UI.user_error!("Missing required parameter :app") unless app_name
    config = load_app_config(app_name)
    ios_bundle_id = config["iosBundleId"]
    project_path = config["projectPath"]

    setup_asc_api_key

    create_keychain(
      name: "fastlane_keychain",
      password: "fastlane_keychain",
      timeout: 1800,
      default_keychain: true,
      unlock: true,
      lock_when_sleeps: false
    )

    match(
      app_identifier: ios_bundle_id,
      type: "appstore",
      readonly: true,
      keychain_name: "fastlane_keychain",
      keychain_password: "fastlane_keychain"
    )

    project_dir = File.join(REPO_ROOT, project_path)

    Dir.chdir(project_dir) do
      sh("flutter", "build", "ipa", "--release", "--export-options-plist=ios/ExportOptions.plist")
    end

    ipa_dir = File.join(project_dir, "build", "ios", "ipa")
    ipa_path = Dir.glob(File.join(ipa_dir, "*.ipa")).first
    UI.user_error!("No .ipa found in #{ipa_dir}") unless ipa_path

    upload_to_app_store(
      app_identifier: ios_bundle_id,
      ipa: ipa_path,
      submit_for_review: true,
      force: true,
      automatic_release: true,
      skip_screenshots: true,
      skip_metadata: true,
      run_precheck_before_submit: false,
      precheck_include_in_app_purchases: false
    )
  end
end
