ane :increase_version do
    android_version_detail = google_play_track_version_codes(
        json_key: "/Users/distiller/project/apps/daily_memo/android/google_playstore_api_key.json",
        package_name: "com.spiral_daily_dev.apps.daily_memo",
    )

    data = YAML.load_file("/Users/distiller/project/apps/daily_memo/pubspec.yaml")
    android_version = data["version"]
    android_version = android_version.split("+")[0]

    android_version_detail += 1

    sh("sed -i '' -e \"s/version: .*/version: #{android_version}+#{android_version_detail}/\" /Users/distiller/project/apps/daily_memo/pubspec.yaml")

end