name: info_shelf
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0 # 최신 버전으로 업데이트하세요.
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  cached_network_image: 3.3.0
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
