name: utils
description: Shared result types and failure hierarchy for Spiral apps.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.0.6 <4.0.0'

dev_dependencies:
  test: ^1.24.0
  lints: ^3.0.0
